services:
  train:
    build:
      context: .
      dockerfile: Dockerfile
    image: asr-training:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HF_HOME=/workspace/.cache/huggingface
      - HF_DATASETS_CACHE=/workspace/datasets
    volumes:
      - ./data:/workspace/data
      - ./outputs:/workspace/outputs
      - ~/.cache/huggingface:/workspace/.cache/huggingface
      - ./datasets_cache:/workspace/datasets_cache
    shm_size: '16gb'
    command: ["+experiments=production"]

  train-dev:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: asr-training:local
    environment:
      - HF_HOME=/workspace/.cache/huggingface
      - HF_DATASETS_CACHE=/workspace/datasets
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      - PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0
    volumes:
      - ./data:/workspace/data
      - ./outputs:/workspace/outputs
      - ~/.cache/huggingface:/workspace/.cache/huggingface
      - ./datasets_cache:/workspace/datasets_cache
    shm_size: '8gb'
    command: ["hatch", "run", "train-mac"]
    profiles: ["dev"]

  tensorboard:
    image: tensorflow/tensorflow:latest
    ports:
      - "6006:6006"
    volumes:
      - ./logs:/logs
    command: ["tensorboard", "--logdir=/logs", "--host=0.0.0.0"]
    profiles: ["monitoring"]