defaults:
  - model: default
  - data: default
  - training: default
  - _self_

# Output directories - relative to where the command is run
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: true

# Resume from checkpoint
resume_from_checkpoint: null

# Evaluation and prediction logging
log_predictions_every_n_steps: 500  # How often to log predictions to TensorBoard
log_predictions_samples: 10  # Number of samples to evaluate for predictions