defaults:
  - model: default
  - data: default
  - training: default
  - _self_

# Output directories - relative to where the command is run
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: true

# Resume from checkpoint
resume_from_checkpoint: null

# Evaluation mode
eval_checkpoint: null