# Training arguments
output_dir: ./outputs/asr_model
overwrite_output_dir: false

# Training configuration
max_steps: 10000
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
gradient_accumulation_steps: 8
eval_accumulation_steps: 1

# Learning rate
learning_rate: 5e-5
lr_scheduler_type: cosine
warmup_ratio: 0.05
weight_decay: 0.01

# Optimizer
optim: adamw_torch
adam_beta1: 0.9
adam_beta2: 0.98
adam_epsilon: 1e-8

# Logging
logging_dir: ./logs
logging_steps: 10
logging_first_step: true
logging_nan_inf_filter: false
report_to: []

# Evaluation
eval_strategy: steps
eval_steps: 500

# Saving
save_strategy: steps
save_steps: 500
save_total_limit: 3
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false

# Hub
push_to_hub: false

# Performance
dataloader_num_workers: 4
gradient_checkpointing: true
fp16: false
bf16: true
dataloader_pin_memory: true
max_grad_norm: 1.0

# Torch compile (PyTorch 2.0+)
use_torch_compile: false  # Disabled by default
torch_compile_mode: default  # Options: default, reduce-overhead, max-autotune

# Misc
seed: 42
save_safetensors: true
disable_tqdm: false
log_level: info

# Required by HF Trainer
remove_unused_columns: false
label_names:
  - labels